dataset:
  path: "./data/dataset_preprocessed.csv"

split:
  test_size: 0.2
  random_state: 42

models:
  logistic_regression:
    type: "logistic_regression"
    params:
      max_iter: 200

  decision_tree:
    type: "decision_tree"
    params:
      max_depth: 5

  random_forest:
    type: "random_forest"
    params:
      n_estimators: 50
